### ISSUE TITLE
cannot import name 'get_args' from 'typing' when importing ramanspy

### ISSUE THREAD

**Issue by tigerwang3133** [barahona-research-group/RamanSPy#1]
reproduce:
import ramanspy as rp

python 3.7.1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ramanspy\__init__.py", line 4, in <module>
    from . import load
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ramanspy\load.py", line 7, in <module>
    from . import core
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ramanspy\core.py", line 10, in <module>
    from . import plot
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ramanspy\plot\__init__.py", line 1, in <module>
    from .plot import spectra, mean_spectra, peak_dist, image, volume, peaks, show
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\ramanspy\plot\plot.py", line 7, in <module>
    from typing import List, get_args, Union, TYPE_CHECKING
ImportError: cannot import name 'get_args' from 'typing' (C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\typing.py)

**Comment by dgeorgiev21** [comment]
Thank you for reporting this issue! 

The problem is that typing.get_args was only introduced in Python 3.8 (source: https://docs.python.org/3/library/typing.html#typing.get_args).

I will try to find out if there are workarounds for versions <3.8. Otherwise, I will need to update the Python requirements (currently these are inaccurately set to >=3.7).

In the meantime, is upgrading to a later Python version an option for you?

Thank you for exploring RamanSPy! :)

**Comment by tigerwang3133** [comment]
Thank you so much! I will update my python version.
